version: '3'

services:
  go-dev:
    container_name: go-dev
    build:
      context: .
      dockerfile: go.dockerfile
      args:
        - GITHUB_USER_NAME=$GITHUB_USER_NAME
    tty: true
    volumes:
      - ./code:/go/src/github.com/$GITHUB_USER_NAME
