version: '3'

services:
  go:
    container_name: go-dev
    build:
      context: .
      dockerfile: go.dockerfile
    tty: true
    volumes:
      - ./code/app:/go/src/app
    ports:
      - 4000:4000

  mysql:
    container_name: go-dev-mysql
    build:
      context: .
      dockerfile: mysql.dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE=$MYSQL_DATABASE
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
