version: '3'

services:
  go:
    container_name: go-dev
    build:
      context: .
      dockerfile: df-go.dockerfile
      args:
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_PORT=$POSTGRES_PORT
        - POSTGRES_SERVER=$POSTGRES_SERVER
    tty: true
    volumes:
      - ./code/app:/go/src/app
    ports:
      - 4000:4000
      - 6060:6060
      - 8080:8080

  mysql:
    container_name: go-dev-mysql
    build:
      context: .
      dockerfile: df-mysql.dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE=$MYSQL_DATABASE
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/mysql/initdb.d:/docker-entrypoint-initdb.d

  psql:
    container_name: go-dev-psql
    build:
      context: .
      dockerfile: df-psql.dockerfile
      args:
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./db/psql/initdb.d:/docker-entrypoint-initdb.d
